insert into direcciones (direccion, ciudad) values ('Sur 25 70, Centro', 'Orizaba');
insert into direcciones (direccion, ciudad) values ('Oriente 3 769B, Centro', 'Orizaba');
insert into direcciones (direccion, ciudad) values ('Oriente 5 811A, Centro', 'Orizaba');
insert into direcciones (direccion, ciudad) values ('Norte 12 315, Emiliano Zapata', 'Orizaba');
insert into direcciones (direccion, ciudad) values ('Norte 14, Emiliano Zapata', 'Orizaba');
insert into direcciones (direccion, ciudad) values ('Av. 3 300, Centro', 'Córdoba');
insert into direcciones (direccion, ciudad) values ('Av 9 201, Centro', 'Córdoba');
insert into direcciones (direccion, ciudad) values ('Av 11 1024, Federal', 'Córdoba');
insert into direcciones (direccion, ciudad) values ('Calle 18, San Jose', 'Córdoba');
insert into direcciones (direccion, ciudad) values ('Av 9 1617, San Jose', 'Córdoba');
