insert into visitas (idPaciente, fecha, observaciones) values (1, '2019-11-30', 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero');
insert into visitas (idPaciente, fecha, observaciones) values (1, '2019-01-15', 'porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus');
insert into visitas (idPaciente, fecha, observaciones) values (1, '2019-01-06', 'ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl');
insert into visitas (idPaciente, fecha, observaciones) values (1, '2019-03-09', 'nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac');
insert into visitas (idPaciente, fecha, observaciones) values (1, '2019-04-11', 'in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis');
insert into visitas (idPaciente, fecha, observaciones) values (2, '2020-05-07', 'in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean');
insert into visitas (idPaciente, fecha, observaciones) values (2, '2020-01-14', 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in');
insert into visitas (idPaciente, fecha, observaciones) values (2, '2019-06-02', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor');
insert into visitas (idPaciente, fecha, observaciones) values (2, '2019-10-01', 'aenean fermentum donec ut mauris eget massa tempor convallis nulla');
insert into visitas (idPaciente, fecha, observaciones) values (2, '2019-08-27', 'suspendisse potenti cras in purus eu magna vulputate luctus cum');
insert into visitas (idPaciente, fecha, observaciones) values (3, '2019-09-08', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis');
insert into visitas (idPaciente, fecha, observaciones) values (3, '2019-07-31', 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia');
insert into visitas (idPaciente, fecha, observaciones) values (3, '2019-02-13', 'in magna bibendum imperdiet nullam orci pede venenatis non sodales sed');
insert into visitas (idPaciente, fecha, observaciones) values (3, '2019-04-09', 'nam congue risus semper porta volutpat quam pede lobortis ligula');
insert into visitas (idPaciente, fecha, observaciones) values (3, '2020-02-22', 'risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit');
insert into visitas (idPaciente, fecha, observaciones) values (4, '2019-03-26', 'lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna');
insert into visitas (idPaciente, fecha, observaciones) values (4, '2020-04-18', 'pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate');
insert into visitas (idPaciente, fecha, observaciones) values (4, '2019-02-06', 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede');
insert into visitas (idPaciente, fecha, observaciones) values (4, '2019-03-18', 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel');
insert into visitas (idPaciente, fecha, observaciones) values (4, '2019-10-14', 'convallis duis consequat dui nec nisi volutpat eleifend donec ut');
insert into visitas (idPaciente, fecha, observaciones) values (5, '2019-11-25', 'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus');
insert into visitas (idPaciente, fecha, observaciones) values (5, '2019-02-01', 'nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit');
insert into visitas (idPaciente, fecha, observaciones) values (5, '2020-02-06', 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet');
insert into visitas (idPaciente, fecha, observaciones) values (5, '2019-02-19', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus');
insert into visitas (idPaciente, fecha, observaciones) values (5, '2019-02-21', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into visitas (idPaciente, fecha, observaciones) values (6, '2020-04-21', 'pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut');
insert into visitas (idPaciente, fecha, observaciones) values (6, '2020-03-08', 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt');
insert into visitas (idPaciente, fecha, observaciones) values (6, '2020-01-01', 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti');
insert into visitas (idPaciente, fecha, observaciones) values (6, '2019-06-16', 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim');
insert into visitas (idPaciente, fecha, observaciones) values (6, '2019-01-20', 'venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus');
insert into visitas (idPaciente, fecha, observaciones) values (7, '2019-11-27', 'consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into visitas (idPaciente, fecha, observaciones) values (7, '2019-07-13', 'elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis');
insert into visitas (idPaciente, fecha, observaciones) values (7, '2020-02-13', 'consequat lectus in est risus auctor sed tristique in tempus sit amet');
insert into visitas (idPaciente, fecha, observaciones) values (7, '2020-02-17', 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan');
insert into visitas (idPaciente, fecha, observaciones) values (7, '2019-03-29', 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla');
insert into visitas (idPaciente, fecha, observaciones) values (8, '2019-10-24', 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus');
insert into visitas (idPaciente, fecha, observaciones) values (8, '2019-12-18', 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas');
insert into visitas (idPaciente, fecha, observaciones) values (8, '2019-10-30', 'varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et');
insert into visitas (idPaciente, fecha, observaciones) values (8, '2019-11-06', 'nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse');
insert into visitas (idPaciente, fecha, observaciones) values (8, '2019-12-22', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non');
insert into visitas (idPaciente, fecha, observaciones) values (9, '2019-05-16', 'accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum');
insert into visitas (idPaciente, fecha, observaciones) values (9, '2019-12-28', 'sapien cursus vestibulum proin eu mi nulla ac enim in');
insert into visitas (idPaciente, fecha, observaciones) values (9, '2019-03-14', 'at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices');
insert into visitas (idPaciente, fecha, observaciones) values (9, '2020-03-20', 'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius');
insert into visitas (idPaciente, fecha, observaciones) values (9, '2019-11-05', 'praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum');
insert into visitas (idPaciente, fecha, observaciones) values (10, '2020-03-12', 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo');
insert into visitas (idPaciente, fecha, observaciones) values (10, '2019-04-08', 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu');
insert into visitas (idPaciente, fecha, observaciones) values (10, '2019-08-15', 'eget nunc donec quis orci eget orci vehicula condimentum curabitur in');
insert into visitas (idPaciente, fecha, observaciones) values (10, '2020-04-14', 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus');
insert into visitas (idPaciente, fecha, observaciones) values (10, '2019-05-15', 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam');
